name: Build BlazorApp1
run-name: Building and executing the C# project in this repository
on: 
  push:
  workflow_dispatch: 

env:
  AZURE_WEBAPP_NAME: microtrac   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './BlazorApp1/BlazorApp1/bin/Release/net8.0/publish'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'

jobs:
  Building-And-Executing-Project:
    runs-on: windows-latest
    steps:
      
    - uses: actions/checkout@v4
    - name: Setup dotnet 8.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Build with dotnet
      run: dotnet build BlazorApp1/BlazorApp1.sln
    - name: Publish app
      run: dotnet publish BlazorApp1/BlazorApp1.sln
    - name: 'Web App Deployment'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
